### ISSUE TITLE
utf-8 checks in path names

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#39] opened 2019-05-14 17:04 UTC
how to fail if another standard is being used?

**Comment by petersilva** [comment] 2019-05-14 22:38
As discussed we check that the bytes are well-formed utf8 and refuse the file otherwise.
This only runs on recent versions of linux, and debian linux made utf8 the default with Etch, released in 2010.  so non-utf systems should be pretty darn rare.  There isn't any common reason to run a character set other than utf8, so I think it is reasonable to just reject paths that include non utf-8 characters.

**Comment by petersilva** [comment] 2019-05-14 22:46
googled a bit: https://stackoverflow.com/questions/1031645/how-to-detect-utf-8-in-plain-c
The is_utf8 implementation there looks nice.  just include the link as a credit. other implementation explicitly uses a DFSA for extra academic cred, but I think the is_utf8 is more straighforward.

**Comment by msaraga** [comment] 2019-05-15 15:21
#36

**Comment by petersilva** [comment] 2019-05-15 17:27
This patch looks good and will merge, but I don't think it is just paths... I think we should limit all header values to utf8.   Please add the same test to both name and value in amqp_header_add, and if either of the two fail the test, then we don't include the header in the message (print an error message, and return without adding it to the headers.)

**Comment by habilinour** [comment] 2019-06-25 19:01
Still corrupted oldname

oldname:	Not UTF-8, base64 is: IKcUV/x/AAB2AAAAAAAAADpKRQi6KgAAAAAAAAAAAABzL3N1aXRlcy9wYXIvcmV3cHNfMjAxOTA1
MDEvZm9yZWNhc3Qvd29yay8yMDE5MDYyNTEyMDAwMC9yZXdwcy9jbWRlX3Bvc3SYEEUIuioAAAAA
AAAAAAAAIKgUV/x/AAB2AAAAAAAAADpKRQi6KgAAYLwUV/x/AAD35kEHuioAAAEAAABSRVMvAAAA
AAAAAAAxMl8wNTRfVrjBygi6KgAAnU8VV/x/AABgvBRX/H8AAOsAAAAAAAAApVZCB7oqAAAcAAAA
AAAAACCnFFf8fwAAHAAAAAAAAACdTxVX/H8A
content_type:	text/plain
Payload
235 bytes
Encoding: string
	
20190625174605.741620636 file: /fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/products_dbase/images_ens_prog/2019062512/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_024.png


oldname:	Not UTF-8, base64 is: IKcUV/x/AAB2AAAAAAAAADpKRQi6KgAAAAAAAAAAAABzL3N1aXRlcy9wYXIvcmV3cHNfMjAxOTA1
MDEvZm9yZWNhc3Qvd29yay8yMDE5MDYyNTEyMDAwMC9yZXdwcy9jbWRlX3Bvc3RfcHJvY2Vzc2lu
Zy9pbWFnZXNfZW5zZW1ibGVfcHJvZy9wbG90X2Vuc2VtYmxlX2ZzdC93b3JrL0ZJR1VSRVMvMjAx
OTA2MjUxMl8wNTRfVjhfZ3JlYXRAbGFrZXNfSV9XQVZFX1dIQHBhcm1AbWF4QG1lZGlhbi1pcXIt
dGltZUBtYXhAbWVkaWFuLWlxckABUBVX/H8A
content_type:	text/plain
Payload
235 bytes
Encoding: string
	
20190625174605.743977535 file: /fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/products_dbase/images_ens_prog/2019062512/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_048.png

**Comment by petersilva** [comment] 2019-06-26 07:31
Does path exceed 255?

**Comment by habilinour** [comment] 2019-06-26 17:53
Yes it does. The debug log shows header oldname too long (259)  and it tries to truncate it

2019-06-26 17:11:46,222 [DEBUG] applying realpath to abspath /fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/products_dbase/images_ens_prog/2019062512/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_024.png
2019-06-26 17:11:46,222 [WARNING] header oldname too long (259 bytes), truncating to: /fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/work/20190625120000/rewps/cmde_post_processing/images_ensemble_prog/plot_ensemble_fst/work/FIGURES/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_024
2019-06-26 17:11:46,223 [INFO] published: 20190626171146.222297825 file: /fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/products_dbase/images_ens_prog/2019062512/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_024.png topic=v02.post.fs.site1.ops.eccc.cmod.prod.hubs.suites.par.rewps_20190501.forecast.products_dbase.images_ens_prog.2019062512 sum=n,823a92db6a27e095f9805aea5f002e74 source=MSC-SCI-CMC to_clusters=DDSR.SCIENCE from_cluster=ddsr.science.gc.ca mtime=20190626171105.530554 atime=20190626171105.408393601 mode=0644 parts=1,363048,1,0,0 oldname=/fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/work/20190625120000/rewps/cmde_post_processing/images_ensemble_prog/plot_ensemble_fst/work/FIGURES/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_024.png

**Comment by habilinour** [comment] 2019-07-02 16:36
The files with over 255 bytes in the the path are causing the corruption to oldname header because the short AMQP strings are limited to 255 bytes. The log shows the filenames are truncated to meet the AMQP data type (short strings) but the post does show the filenames with the initial path which exceeds 255 bytes.

**Comment by petersilva** [comment] 2019-07-02 19:32
way to fix this:

* implement v03 in the C code ( #18 ), which stores  attributes in the message body as part of a json string ( no 255 character limit.) 

* change v02 to separate directory and filename (olddir & oldname,   newdir & newname) to get 255+255 as new limit.  requires implementation in both python and C... likely less work than v03, but just a stopgap unnessesary if v03 happens.


I don´t have other ideas, perhaps others do... I think v03 is perhaps more work, but more worth it... need to get there anyways. For this bug, perhaps the immediate thing is to detect the problem, and alert about it.
I imagine the mirroring is still working, it is just either missing (or perhaps merely unnecessarily copying an extra time?) a few files.  probably not a big deal for the mirror.

**Comment by racetted** [comment] 2019-07-02 19:52
@petersilva  In this case, the garbage put in the oldname string seems to cause the subscribers to continually receive the faulty messages, unless that's part of the retry functionality. 

As for the preferred solution, moving to v03 sounds like the right plan, but requires more work than intended in the following weeks.  

Would changing message format impact the API provided to the plugins? Or is that handled by some sort of message preprocessing by the python code before it gets to the plugin framework?  

How much work are we talking about here?

**Comment by petersilva** [comment] 2019-07-02 20:30
It is a few weeks, perhaps one month, of work, for a knowledgeable developer. It took three months to get right on the python side, but working from a reference, should go much faster, but C is harder to work with... I´m guessing a month or so.   I´m a bit confused... with the message being talked about, the current version of the shim library should avoid posting the messages entirely.  There is nothing corrupt for the subscribers to see.  You are still seeing subscriber retry loops?  shouldn´t be there, if we understand the mechanism.

**Comment by racetted** [comment] 2019-07-03 12:01
The message is UTF-8 as it goes out, but the broker or AMQP or something in  the middle puts garbage in instead. So from what I see, the code to ignore it doesn't get run, and the subcribers get said garbage and goes in a retry loop.

**Comment by habilinour** [comment] 2019-07-03 13:32
The issue is not with non-UTF-8 chars but the shim lib posts a message with a header that exceeds 255 bytes, 
 oldname=/fs/site1/ops/eccc/cmod/prod/hubs/suites/par/rewps_20190501/forecast/work/20190625120000/rewps/cmde_post_processing/images_ensemble_prog/plot_ensemble_fst/work/FIGURES/2019062512_054_V8_great@lakes_I_WAVE_WH@parm@max@median-iqr-time@max@median-iqr@024_024.png

**Comment by petersilva** [comment] 2019-07-03 20:18
We should probably put a quick patch in to suppress the message when the header is too long.
that will prevent the problem for now, and longer term solution would be v03.
sigh... unless there is a volunteer, I will get to it, when back from vacation...

**Comment by petersilva** [comment] 2019-07-22 16:11
latest version, v2.19.07b1, has been released with support for v03 posting (no receipt.)  Interop with the current python code was tested, but v03 was evolving through the spring in the python so the code on the protocol/nfs nodes must be upgraded also (currently running 2.18, need >= 2.19.04 ) To use the new protocol, one must tweak the configs:

in the shim library configuration, add:   post_topic_prefix v03.post
in the subscribers, add: topic_prefix v03.post

We´ll see how soon we can get things upgraded to try it out.

**Comment by petersilva** [comment] 2019-09-20 11:09
It's in operations now. problem gone.

**Closed by petersilva** 2019-09-20 11:09 UTC
Labels: enhancement, likely-fixed
